version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=localhost:3001
    depends_on:
      - api
